version: "2"
services:
  frontend:
    container_name: frontend
    restart: always
    build: ../Coronahelfer-Hackathon-Frontend 
    volumes:
      - '../Coronahelfer-Hackathon-Frontend:/app'
    ports: 
      - "8080:80"
    depends_on:
      - app
    links:
      - app
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8081:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"